### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Romamok** [cee-dee/dagger-by-example#1]
Keeping a reference to Fragment's view causes a memory leak
https://github.com/cee-dee/dagger-by-example/blob/36545a1db99fcc38a60938411f239af43f5e1f93/app/src/main/java/com/example/daggerbyexample/FirstFragment.kt#L15

fix
https://stackoverflow.com/questions/58080268/keeping-a-reference-to-a-view-in-a-fragment-causes-memory-leaks/58181389

**Comment by cee-dee** [comment]
Thanks for pointing out a potential memory leak here!

As your linked StackOverflow post states: "When there is no forward transaction from a fragment, there is nothing wrong with saving views as a strong reference as they will be cleared in onDetach()". So afaik there's no need to fix it for this example.

Besides that, one could use ViewBinding to avoid the View lookup.

I won't change anything here, since it doesn't make any difference on understanding Dagger.
